// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.6
// source: control_service.proto

package polardb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type InsSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host     string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port     int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Database string `protobuf:"bytes,5,opt,name=database,proto3" json:"database,omitempty"`
	Instype  string `protobuf:"bytes,6,opt,name=instype,proto3" json:"instype,omitempty"` // "db", "maxscale", "cm"
}

func (x *InsSpec) Reset() {
	*x = InsSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsSpec) ProtoMessage() {}

func (x *InsSpec) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsSpec.ProtoReflect.Descriptor instead.
func (*InsSpec) Descriptor() ([]byte, []int) {
	return file_control_service_proto_rawDescGZIP(), []int{0}
}

func (x *InsSpec) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *InsSpec) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *InsSpec) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *InsSpec) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *InsSpec) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *InsSpec) GetInstype() string {
	if x != nil {
		return x.Instype
	}
	return ""
}

type SyncInstanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SystemIdentify string   `protobuf:"bytes,1,opt,name=system_identify,json=systemIdentify,proto3" json:"system_identify,omitempty"`
	LogicalInsname string   `protobuf:"bytes,4,opt,name=logical_insname,json=logicalInsname,proto3" json:"logical_insname,omitempty"`
	Ins            *InsSpec `protobuf:"bytes,2,opt,name=ins,proto3" json:"ins,omitempty"`
	Rw             *InsSpec `protobuf:"bytes,3,opt,name=rw,proto3" json:"rw,omitempty"`
}

func (x *SyncInstanceRequest) Reset() {
	*x = SyncInstanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncInstanceRequest) ProtoMessage() {}

func (x *SyncInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncInstanceRequest.ProtoReflect.Descriptor instead.
func (*SyncInstanceRequest) Descriptor() ([]byte, []int) {
	return file_control_service_proto_rawDescGZIP(), []int{1}
}

func (x *SyncInstanceRequest) GetSystemIdentify() string {
	if x != nil {
		return x.SystemIdentify
	}
	return ""
}

func (x *SyncInstanceRequest) GetLogicalInsname() string {
	if x != nil {
		return x.LogicalInsname
	}
	return ""
}

func (x *SyncInstanceRequest) GetIns() *InsSpec {
	if x != nil {
		return x.Ins
	}
	return nil
}

func (x *SyncInstanceRequest) GetRw() *InsSpec {
	if x != nil {
		return x.Rw
	}
	return nil
}

type SyncInstanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 返回码
	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SyncInstanceResponse) Reset() {
	*x = SyncInstanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncInstanceResponse) ProtoMessage() {}

func (x *SyncInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncInstanceResponse.ProtoReflect.Descriptor instead.
func (*SyncInstanceResponse) Descriptor() ([]byte, []int) {
	return file_control_service_proto_rawDescGZIP(), []int{2}
}

func (x *SyncInstanceResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SyncInstanceResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_control_service_proto protoreflect.FileDescriptor

var file_control_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x64, 0x62,
	0x22, 0x9f, 0x01, 0x0a, 0x07, 0x49, 0x6e, 0x73, 0x53, 0x70, 0x65, 0x63, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x73, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6e, 0x73, 0x74, 0x79,
	0x70, 0x65, 0x22, 0xad, 0x01, 0x0a, 0x13, 0x53, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x79, 0x12, 0x27, 0x0a, 0x0f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x69,
	0x6e, 0x73, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6c, 0x6f,
	0x67, 0x69, 0x63, 0x61, 0x6c, 0x49, 0x6e, 0x73, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x03,
	0x69, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x6f, 0x6c, 0x61,
	0x72, 0x64, 0x62, 0x2e, 0x49, 0x6e, 0x73, 0x53, 0x70, 0x65, 0x63, 0x52, 0x03, 0x69, 0x6e, 0x73,
	0x12, 0x20, 0x0a, 0x02, 0x72, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70,
	0x6f, 0x6c, 0x61, 0x72, 0x64, 0x62, 0x2e, 0x49, 0x6e, 0x73, 0x53, 0x70, 0x65, 0x63, 0x52, 0x02,
	0x72, 0x77, 0x22, 0x3c, 0x0a, 0x14, 0x53, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x32, 0x5d, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x53, 0x79, 0x6e, 0x63, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x12, 0x1c, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x64, 0x62, 0x2e, 0x53, 0x79, 0x6e,
	0x63, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x64, 0x62, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_control_service_proto_rawDescOnce sync.Once
	file_control_service_proto_rawDescData = file_control_service_proto_rawDesc
)

func file_control_service_proto_rawDescGZIP() []byte {
	file_control_service_proto_rawDescOnce.Do(func() {
		file_control_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_control_service_proto_rawDescData)
	})
	return file_control_service_proto_rawDescData
}

var file_control_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_control_service_proto_goTypes = []interface{}{
	(*InsSpec)(nil),              // 0: polardb.InsSpec
	(*SyncInstanceRequest)(nil),  // 1: polardb.SyncInstanceRequest
	(*SyncInstanceResponse)(nil), // 2: polardb.SyncInstanceResponse
}
var file_control_service_proto_depIdxs = []int32{
	0, // 0: polardb.SyncInstanceRequest.ins:type_name -> polardb.InsSpec
	0, // 1: polardb.SyncInstanceRequest.rw:type_name -> polardb.InsSpec
	1, // 2: polardb.ControlService.SyncInstance:input_type -> polardb.SyncInstanceRequest
	2, // 3: polardb.ControlService.SyncInstance:output_type -> polardb.SyncInstanceResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_control_service_proto_init() }
func file_control_service_proto_init() {
	if File_control_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_control_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncInstanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncInstanceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_control_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_service_proto_goTypes,
		DependencyIndexes: file_control_service_proto_depIdxs,
		MessageInfos:      file_control_service_proto_msgTypes,
	}.Build()
	File_control_service_proto = out.File
	file_control_service_proto_rawDesc = nil
	file_control_service_proto_goTypes = nil
	file_control_service_proto_depIdxs = nil
}
