{
 "title": "PolarDB 开源版本监控",
 "tags": [
  "PolarDB",
  "GAWR"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "数据源", "query": "postgres" },
   {
    "name": "LogicInstanceShow",
    "label": "逻辑实例ID",
    "query": "SELECT polar_gawr_collection.list_logic_ins_name();"
   },
   {
    "name": "PhysicalInstance",
    "label": "物理实例ID",
    "query": "SELECT  physical_ins_name FROM $LogicInstance.dim_ins_info  WHERE physical_ins_name != 'others'"
   },
   {
    "name": "LogicInstance",
    "label": "逻辑实例id",
    "query": "SELECT *  FROM polar_gawr_collection.get_logic_ins_schema('$LogicInstanceShow')"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "基本信息",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  time - time % ((($__interval_ms / 1000)::INTEGER)::integer) AS time,\n  MAX(host || ':' || port) AS Endpoint,\n  MAX(role) AS Role,\n  MAX(version) AS Version\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "规格信息",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  MAX(cpu_cores) AS \"cpu cores\",\n  ROUND((MAX(mem_total) / 1024.0)::NUMERIC, 2) AS \"memory(GB)\",\n  ROUND((MAX(fs_size_total) / 1024.0)::NUMERIC, 2) AS \"disk size(GB)\"\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(commits_delta+rollbacks_delta) AS TPS\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(active_connections) AS 活跃连接\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(cpu_total_usage)\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(mem_total_usage)\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "缓存命中率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(blks_hit_delta / (blks_hit_delta + blks_read_delta + 1))\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "空间使用率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(fs_blocks_usage)\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Active Session",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  wait_event_type::text || ':' || wait_event AS metric,\n  CASE WHEN ($__interval_ms / 1000) >= 3600 THEN ROUND(CAST(SUM(wait_count) AS NUMERIC) / (($__interval_ms / 3600 / 1000)::INTEGER), 2)::FLOAT\n      WHEN ($__interval_ms / 1000) >= 60 THEN ROUND(CAST(SUM(wait_count) AS NUMERIC) / (($__interval_ms / 60 / 1000)::INTEGER), 2)::FLOAT\n      ELSE ROUND(CAST(SUM(wait_count) AS NUMERIC) / (($__interval_ms / 1000)::INTEGER), 2)::FLOAT END AS wait_count\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_aas_history, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER), metric\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Top SQL Wait Events",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "constant": 6.5,
     "rawSql": "SELECT\n  queryid, SUM(wait_count) AS 总等待事件, array_agg(wait_event || ': ' || ROUND(wait_count::NUMERIC, 2) ORDER BY wait_count DESC) FILTER (WHERE wait_count > 0.01) AS 等待事件详情\nFROM (\nSELECT\n  'queryid: ' || queryid AS queryid,\n  wait_event_type || ':' || wait_event AS wait_event,\n  ROUND(CAST(SUM(wait_count) AS NUMERIC) / ($__unixEpochTo() - $__unixEpochFrom()), 2)::FLOAT AS wait_count\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_aas_history, $__unixEpochFrom(), $__unixEpochTo(), ($__unixEpochTo() - $__unixEpochFrom())::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}' AND queryid != '0'\nGROUP BY queryid, wait_event_type || ':' || wait_event\n) a\nGROUP BY queryid\nORDER BY SUM(wait_count) DESC \nLIMIT 10"
    }
   ]
  },
  {
   "title": "Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
     "options": { "content": "         " },
     "targets": [
      { "constant": 6.5 }
     ]
    },
    {
     "title": "CPU使用率",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(cpu_user_usage) AS 用户态,\n  AVG(cpu_sys_usage) AS 系统态\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "CPU: 按进程类型堆叠",
     "type": "graph",
     "gridPos": { "h": 12, "w": 15, "x": 9, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "yaxes": [
      { "format": "%" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT time, metric, cpu FROM (\nSELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  backend_type AS metric,\n  AVG(cpu_user+cpu_sys) AS cpu\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_process, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}' AND\n  $__unixEpochFilter(time)\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER), backend_type\nUNION ALL\nSELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  'postmaster' AS metric,\n  AVG(postmaster_cpu) AS cpu\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}' AND\n  $__unixEpochFilter(time)\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nUNION ALL\nSELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  'logger' AS metric,\n  AVG(logger_cpu) AS cpu\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}' AND\n  $__unixEpochFilter(time)\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nUNION ALL\nSELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  'pgstat' AS metric,\n  AVG(pgstat_cpu) AS cpu\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}' AND\n  $__unixEpochFilter(time)\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\n) a ORDER BY time"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
     "options": { "content": "         " },
     "targets": [
      { "constant": 6.5 }
     ]
    },
    {
     "title": "内存使用率",
     "type": "graph",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "%" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  MAX(mem_total_usage) AS 内存使用率\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Memory: 按进程类型堆叠",
     "type": "graph",
     "gridPos": { "h": 12, "w": 15, "x": 9, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT time, metric, rss FROM (\nSELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  backend_type AS metric,\n  AVG(rss) AS rss\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_process, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER), backend_type\nUNION ALL\nSELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  'postmaster' AS metric,\n  AVG(postmaster_mem) AS rss\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nUNION ALL\nSELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  'pgstat' AS metric,\n  AVG(pgstat_mem) AS rss\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nUNION ALL\nSELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  'logger' AS metric,\n  AVG(logger_mem) AS rss\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\n) a ORDER BY time"
      }
     ]
    },
    {
     "title": "Memory Detail",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "MB" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(mem_rss) AS rss,\n  AVG(mem_cache) AS cache,\n  AVG(mem_inactiverss) AS inactiverss,\n  AVG(mem_inactivecache) AS inactivecache,\n  AVG(mem_mapped_file) AS mapped_file\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Top 内存占用会话 (200MB以上)",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 73 },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "                            SELECT pid AS 进程id, rss_mb AS \"RSS(MB)\", TO_CHAR(TO_TIMESTAMP(time), 'YYYY-MM-DD HH24:MI:SS') AS 对应时间点, query AS query\n                            FROM ${LogicInstance}.view_fact_polar_stat_max_memory_sql \n                            WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n                            ORDER BY rss_mb DESC, time DESC LIMIT 10\n\n"
      }
     ]
    },
    {
     "title": "IO",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
     "options": { "content": "         " },
     "targets": [
      { "constant": 6.5 }
     ]
    },
    {
     "title": "数据盘IOPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(pls_iops_read) AS read,\n  AVG(pls_iops_write) AS write\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "数据盘吞吐",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(pls_throughput_read) AS read,\n  AVG(pls_throughput_write) AS write\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "数据盘平均延迟",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(pls_latency_read) AS read,\n  AVG(pls_latency_write) AS write\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "IO: 进程类型维度",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
     "options": { "content": "         " },
     "targets": [
      { "constant": 6.5 }
     ]
    },
    {
     "title": "IOPS: 按进程类型堆叠",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 96 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  backend_type AS metric,\n  AVG(shared_read_ps+shared_write_ps) AS IOPS\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_process, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER), backend_type\nORDER BY 1"
      }
     ]
    },
    {
     "title": "IO吞吐: 按进程类型堆叠",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  backend_type AS metric,\n  AVG(shared_read_throughput+shared_write_throughput) AS IOPS\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_process, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER), backend_type\nORDER BY 1"
      }
     ]
    },
    {
     "title": "IO: 文件类型维度",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
     "options": { "content": "         " },
     "targets": [
      { "constant": 6.5 }
     ]
    },
    {
     "title": "read iops",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 111 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  filetype AS metric,\n  AVG(read_count) AS read_iops\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_io_info, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}' AND fileloc='pfs'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER), filetype\nORDER BY 1"
      }
     ]
    },
    {
     "title": "write iops",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 111 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  filetype AS metric,\n  AVG(write_count) AS write_iops\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_io_info, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}' AND fileloc='pfs'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER), filetype\nORDER BY 1"
      }
     ]
    },
    {
     "title": "seek iops",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 111 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  filetype AS metric,\n  AVG(seek_count) AS seek_iops\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_io_info, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}' AND fileloc='pfs'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER), filetype\nORDER BY 1"
      }
     ]
    },
    {
     "title": "open iops",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 111 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  filetype AS metric,\n  AVG(open_count) AS open_iops\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_io_info, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}' AND fileloc='pfs'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER), filetype\nORDER BY 1"
      }
     ]
    },
    {
     "title": "IO: 延迟",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
     "options": { "content": "         " },
     "targets": [
      { "constant": 6.5 }
     ]
    },
    {
     "title": "read延迟分布",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 121 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(num_lessthan200us / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"[0, 200us]\",\n  AVG(num_lessthan400us / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"(200us, 400us]\",\n  AVG(num_lessthan1ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"(400us, 1ms]\",\n  AVG(num_lessthan10ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"(1ms, 10ms]\",\n  AVG(num_lessthan100ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"(10ms, 100ms]\",\n  AVG(num_morethan100ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"(100ms, )\"\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_io_latency, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}' AND iotype='read'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "write延迟分布",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 121 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(num_lessthan200us / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"[0, 200us]\",\n  AVG(num_lessthan400us / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"(200us, 400us]\",\n  AVG(num_lessthan1ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"(400us, 1ms]\",\n  AVG(num_lessthan10ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"(1ms, 10ms]\",\n  AVG(num_lessthan100ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"(10ms, 100ms]\",\n  AVG(num_morethan100ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"(100ms, )\"\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_io_latency, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}' AND iotype='write'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "seek延迟分布",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 121 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(num_lessthan200us / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"[0, 200us]\",\n  AVG(num_lessthan400us / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"(200us, 400us]\",\n  AVG(num_lessthan1ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"(400us, 1ms]\",\n  AVG(num_lessthan10ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"(1ms, 10ms]\",\n  AVG(num_lessthan100ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"(10ms, 100ms]\",\n  AVG(num_morethan100ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"(100ms, )\"\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_io_latency, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}' AND iotype='seek'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "open延迟分布",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 121 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(num_lessthan200us / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"[0, 200us]\",\n  AVG(num_lessthan400us / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"(200us, 400us]\",\n  AVG(num_lessthan1ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"(400us, 1ms]\",\n  AVG(num_lessthan10ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"(1ms, 10ms]\",\n  AVG(num_lessthan100ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"(10ms, 100ms]\",\n  AVG(num_morethan100ms / (num_lessthan200us+num_lessthan400us+num_lessthan1ms+num_lessthan10ms+num_lessthan100ms+num_morethan100ms+1)) AS \"(100ms, )\"\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_polar_stat_io_latency, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}' AND iotype='open'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "磁盘空间",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 },
     "options": { "content": "         " },
     "targets": [
      { "constant": 6.5 }
     ]
    },
    {
     "title": "资源使用",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(fs_blocks_usage) AS block使用率,\n  AVG(fs_inodes_usage) AS inode使用率\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "空间分布",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(polar_base_dir_size) AS 数据目录大小,\n  AVG(polar_wal_dir_size) AS WAL目录大小\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "锁",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 },
     "options": { "content": "         " },
     "targets": [
      { "constant": 6.5 }
     ]
    },
    {
     "title": "Top 锁阻塞情况",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 141 },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n                                   datname AS 数据库,\n                                   relation AS 表,\n                                   locktype AS 锁类型,\n                                   mode AS 锁级别,\n                                   query AS query,\n                                   SUM(total_num)::BIGINT AS 累计阻塞采样会话数\n                               FROM ${LogicInstance}.view_fact_polar_lock_contention_history\n                               WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n                               GROUP BY 数据库, 表, 锁类型, 锁级别, query\n                               ORDER BY 累计阻塞采样会话数 DESC LIMIT 10"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(connections) AS total,\n  AVG(active_connections) AS active,\n  AVG(idle_connections) AS idle\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Transaction",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(active_transactions) AS active,\n  AVG(idle_transactions) AS idle\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "TPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(commits_delta) AS commits,\n  AVG(rollbacks_delta) AS rollbacks,\n  AVG(commits_delta+rollbacks_delta) AS TPS\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Rows",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(tup_returned_delta) AS tup_returned,\n  AVG(tup_fetched_delta) AS tup_fetched,\n  AVG(tup_inserted_delta) AS tup_inserted,\n  AVG(tup_updated_delta) AS tup_updated,\n  AVG(tup_deleted_delta) AS tup_deleted\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "DB Read",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(blks_read_delta) AS blks_read,\n  AVG(blks_hit_delta) AS blks_hit\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "DB Write",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(buffers_checkpoint_delta) AS checkpoint,\n  AVG(buffers_backend_delta) AS backend,\n  AVG(buffers_clean_delta) AS bgwriter\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      },
      {
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "DB Age",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(db_age) AS db_age\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Swell time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(swell_time) AS swell_time\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "dirty page",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(polar_dirtypage_size) AS polar_dirtypage_size\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "CopyBuffer",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(polar_copybuffer_used_size) AS polar_copybuffer_used_size\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "PolarDB 位点",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(wp_cp_latency_mb) AS wp_cp_latency_mb,\n  AVG(ap_cp_latency_mb) AS ap_cp_latency_mb,\n  AVG(wp_ap_latency_mb) AS wp_ap_latency_mb\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Standby/RO 回放延迟",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  application_name AS metric,\n  AVG(replay_latency_mb) AS replay_latency_mb\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_replay_latency_mb, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER), application_name\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Logindex MemTable",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n  time - time % (($__interval_ms / 1000)::INTEGER) AS time,\n  AVG(logindex_mem_tbl_size) AS logindex_memtables\nFROM polar_gawr_collection.get_data_from_proper_table(NULL::${LogicInstance}.view_fact_dbmetrics, $__unixEpochFrom(), $__unixEpochTo(), ($__interval_ms / 1000)::INTEGER)\nWHERE\n  physical_ins_name='${PhysicalInstance}'\nGROUP BY time - time % (($__interval_ms / 1000)::INTEGER)\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "以下数据需要开启pg_stat_statements插件",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
     "options": { "content": "         " },
     "targets": [
      { "constant": 6.5 }
     ]
    },
    {
     "title": "Top 累计执行时间",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "\n\n\n                               WITH x AS (\n                                      SELECT * FROM ${LogicInstance}.view_fact_polar_stat_top_sql\n                                      WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n                               )\n                               SELECT queryid AS queryid, query AS query,\n                                   \n                                   ROUND(SUM(total_time)::NUMERIC, 2) AS \"累计执行时间(ms)\",\n                                   SUM(calls)::BIGINT AS value_执行次数,\n                                   ROUND((SUM(total_time) / SUM(calls))::NUMERIC, 2) AS \"平均执行时间(ms)\",\n                                   ROUND((SUM(blk_iotime) / SUM(total_time) * 100)::NUMERIC, 2) AS \"IO时间占比(%)\",\n                                   SUM(logical_read)::BIGINT AS 逻辑读,\n                                   SUM(blks_read)::BIGINT AS 物理读,\n                                   SUM(logical_write)::BIGINT AS 逻辑写,\n                                   SUM(blks_written)::BIGINT AS 物理写,\n                                   SUM(rows)::BIGINT AS 处理行数\n                               FROM x\n                               GROUP BY queryid, query\n                               ORDER BY SUM(total_time) DESC LIMIT 10"
      }
     ]
    },
    {
     "title": "Top 平均执行时间",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 50 },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "\n\n\n                               WITH x AS (\n                                      SELECT * FROM ${LogicInstance}.view_fact_polar_stat_top_sql\n                                      WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n                               )\n                               SELECT queryid, query,\n                                   ROUND(SUM(total_time)::NUMERIC, 2) AS \"累计执行时间(ms)\",\n                                   SUM(calls)::BIGINT AS value_执行次数,\n                                   ROUND((SUM(total_time) / SUM(calls))::NUMERIC, 2) AS \"平均执行时间(ms)\",\n                                   ROUND((SUM(blk_iotime) / SUM(total_time) * 100)::NUMERIC, 2) AS \"IO时间占比(%)\",\n                                   SUM(logical_read)::BIGINT AS 逻辑读,\n                                   SUM(blks_read)::BIGINT AS 物理读,\n                                   SUM(logical_write)::BIGINT AS 逻辑写,\n                                   SUM(blks_written)::BIGINT AS 物理写,\n                                   SUM(rows)::BIGINT AS 处理行数\n                               FROM x\n                               GROUP BY queryid, query\n                               ORDER BY \"平均执行时间(ms)\" DESC LIMIT 10"
      }
     ]
    },
    {
     "title": "Top 读IO",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 62 },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "\n\n\n                               WITH x AS (\n                                      SELECT * FROM ${LogicInstance}.view_fact_polar_stat_top_sql\n                                      WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n                               )\n                               SELECT queryid, query,\n                                   ROUND(SUM(blk_read_time)::NUMERIC, 2) AS \"累计读IO时间(ms)\",\n                                   SUM(calls)::BIGINT AS value_执行次数,\n                                   ROUND((SUM(total_time) / SUM(calls))::NUMERIC, 2) AS \"平均执行时间(ms)\",\n                                   ROUND((SUM(blk_read_time) / SUM(calls))::NUMERIC, 2) AS \"平均读IO时间(ms)\",\n                                   ROUND((SUM(blk_read_time) / SUM(total_time) * 100)::NUMERIC, 2) AS \"读IO耗时占比(%)\",\n                                   ROUND((SUM(logical_read) / SUM(calls))::NUMERIC, 2) AS 平均逻辑读,\n                                   ROUND((SUM(blks_read) / SUM(calls))::NUMERIC, 2) AS 平均物理读,\n                                   CASE WHEN SUM(logical_read) < 1 THEN 100 ELSE ROUND((SUM(blks_hit) / SUM(logical_read) * 100)::NUMERIC, 2) END AS \"读缓存命中率(%)\",\n                                   ROUND((SUM(rows) / SUM(calls))::NUMERIC, 2) AS 平均处理行数\n                               FROM x\n                               GROUP BY queryid, query\n                               ORDER BY SUM(blk_read_time) DESC LIMIT 10"
      }
     ]
    },
    {
     "title": "Top 写IO",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 74 },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "\n\n\n                               WITH x AS (\n                                      SELECT * FROM ${LogicInstance}.view_fact_polar_stat_top_sql\n                                      WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n                               )\n                               SELECT queryid, query,\n                                   ROUND(SUM(blk_write_time)::NUMERIC, 2) AS \"累计写IO时间(ms)\",\n                                   SUM(calls)::BIGINT AS value_执行次数,\n                                   ROUND((SUM(total_time) / SUM(calls))::NUMERIC, 2) AS \"平均执行时间(ms)\",\n                                   ROUND((SUM(blk_write_time) / SUM(calls))::NUMERIC, 2) AS \"平均写IO时间(ms)\",\n                                   ROUND((SUM(blk_write_time) / SUM(total_time) * 100)::NUMERIC, 2) AS \"写IO耗时占比(%)\",\n                                   ROUND((SUM(logical_write) / SUM(calls))::NUMERIC, 2) AS 平均逻辑写,\n                                   ROUND((SUM(blks_written) / SUM(calls))::NUMERIC, 2) AS 平均物理写,\n                                   CASE WHEN SUM(logical_write) < 1 THEN 100 ELSE ROUND((SUM(blks_hit) / SUM(logical_write) * 100)::NUMERIC, 2) END AS \"写缓存命中率(%)\",\n                                   ROUND((SUM(rows) / SUM(calls))::NUMERIC, 2) AS 平均处理行数\n                               FROM x\n                               GROUP BY queryid, query\n                               ORDER BY SUM(blk_write_time) DESC LIMIT 10"
      }
     ]
    }
   ]
  },
  {
   "title": "Table & Index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "以下数据查询间隔建议放大至一小时以上",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
     "options": { "content": "         " },
     "targets": [
      { "constant": 6.5 }
     ]
    },
    {
     "title": "Top 表级顺序扫描",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "\n                               WITH x AS (\n                                   SELECT *\n                                   FROM ${LogicInstance}.view_fact_polar_stat_user_tables\n                                   WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n                               )\n                               SELECT\n                                   dbname AS 数据库,\n                                   schemaname AS schema,\n                                   relname AS 表,\n                                   SUM(seq_scan)::BIGINT AS 顺序扫描次数,\n                                   SUM(seq_tup_read)::BIGINT AS 扫描行数\n                               FROM x\n                               GROUP BY dbname, schemaname, relname HAVING SUM(seq_tup_read) > 0.1\n                               ORDER BY 扫描行数 DESC LIMIT 10\n                               \n"
      }
     ]
    },
    {
     "title": "Top 表级索引扫描",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 51 },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "                               SELECT\n                                   dbname AS 数据库,\n                                   schemaname AS schema,\n                                   relname AS 表,\n                                   SUM(idx_scan)::BIGINT AS 索引扫描次数,\n                                   SUM(idx_tup_fetch)::BIGINT AS 索引扫描行数\n                               FROM ${LogicInstance}.view_fact_polar_stat_user_tables\n                               WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n                               GROUP BY dbname, schemaname, relname HAVING SUM(idx_tup_fetch) > 0.1\n                               ORDER BY 索引扫描行数 DESC LIMIT 10\n"
      }
     ]
    },
    {
     "title": "Top 表级行数变更",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n                                   dbname AS 数据库,\n                                   schemaname AS schema,\n                                   relname AS 表,\n                                   SUM(n_tup_ins)::BIGINT AS 插入行数,\n                                   SUM(n_tup_upd)::BIGINT AS 更新行数,\n                                   SUM(n_tup_hot_upd)::BIGINT AS HOT更新行数,\n                                   SUM(n_tup_del)::BIGINT AS 删除行数,\n                                   SUM(n_tup_modified)::BIGINT AS 总变更行数\n                               FROM ${LogicInstance}.view_fact_polar_stat_user_tables\n                               WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n                               GROUP BY dbname, schemaname, relname HAVING SUM(n_tup_modified) > 0.1\n                               ORDER BY 总变更行数 DESC LIMIT 10"
      }
     ]
    },
    {
     "title": "Top 表级行数变更",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 75 },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n                                   dbname AS 数据库,\n                                   schemaname AS schema,\n                                   relname AS 表,\n                                   SUM(n_tup_ins)::BIGINT AS 插入行数,\n                                   SUM(n_tup_upd)::BIGINT AS 更新行数,\n                                   SUM(n_tup_hot_upd)::BIGINT AS HOT更新行数,\n                                   SUM(n_tup_del)::BIGINT AS 删除行数,\n                                   SUM(n_tup_modified)::BIGINT AS 总变更行数\n                               FROM ${LogicInstance}.view_fact_polar_stat_user_tables\n                               WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n                               GROUP BY dbname, schemaname, relname HAVING SUM(n_tup_modified) > 0.1\n                               ORDER BY 总变更行数 DESC LIMIT 10"
      }
     ]
    },
    {
     "title": "Top 索引级扫描",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 87 },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n                                   dbname AS 数据库,\n                                   schemaname AS schema,\n                                   relname AS 表,\n                                   indexrelname AS 索引,\n                                   SUM(idx_scan)::BIGINT AS 扫描次数,\n                                   SUM(idx_tup_fetch)::BIGINT AS 返回行数,\n                                   SUM(idx_tup_read)::BIGINT AS 扫描行数\n                               FROM ${LogicInstance}.view_fact_polar_stat_user_indexes\n                               WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n                               GROUP BY 数据库, schema, 表, 索引 HAVING SUM(idx_tup_read) > 0.1\n                               ORDER BY 扫描行数 DESC LIMIT 10"
      }
     ]
    },
    {
     "title": "Top表级读IO",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 99 },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n                                   dbname AS 数据库,\n                                   schemaname AS schema,\n                                   relname AS 表,\n                                   SUM(heap_logical_read)::BIGINT AS 逻辑读,\n                                   SUM(heap_blks_read)::BIGINT AS 物理读,\n                                   ROUND((SUM(heap_blks_hit) / SUM(heap_logical_read) * 100)::NUMERIC, 2) AS \"缓存命中率(%)\"\n                               FROM ${LogicInstance}.view_fact_polar_statio_user_tables\n                               WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n                               GROUP BY 数据库, schema, 表 HAVING SUM(heap_logical_read) > 0.1\n                               ORDER BY 逻辑读 DESC LIMIT 10"
      }
     ]
    },
    {
     "title": "Top 表级索引读IO",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 111 },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n                                   dbname AS 数据库,\n                                   schemaname AS schema,\n                                   relname AS 表,\n                                   SUM(idx_logical_read)::BIGINT AS 逻辑读,\n                                   SUM(idx_blks_read)::BIGINT AS 物理读,\n                                   ROUND((SUM(idx_blks_hit) / (SUM(idx_logical_read)+1) * 100)::NUMERIC, 2) AS \"缓存命中率(%)\"\n                               FROM ${LogicInstance}.view_fact_polar_statio_user_tables\n                               WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n                               GROUP BY 数据库, schema, 表 HAVING SUM(heap_logical_read) > 0.1\n                               ORDER BY 逻辑读 DESC LIMIT 10"
      }
     ]
    },
    {
     "title": "Top 索引级读IO",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 123 },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n                                   dbname AS 数据库,\n                                   schemaname AS schema,\n                                   relname AS 表,\n                                   indexrelname AS 索引,\n                                   SUM(idx_logical_read)::BIGINT AS 逻辑读,\n                                   SUM(idx_blks_read)::BIGINT AS 物理读,\n                                   ROUND((SUM(idx_blks_hit) / SUM(idx_logical_read) * 100)::NUMERIC, 2) AS \"缓存命中率(%)\"\n                               FROM ${LogicInstance}.view_fact_polar_statio_user_indexes\n                               WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}'\n                               GROUP BY 数据库, schema, 表, 索引 HAVING SUM(idx_logical_read) > 0.1\n                               ORDER BY 逻辑读 DESC LIMIT 10"
      }
     ]
    },
    {
     "title": "Top 空间占用",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 135 },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n                                   dbname AS 数据库,\n                                   schemaname AS schema,\n                                   relname AS 表,\n                                   CASE WHEN relkind='r' THEN '表'\n                                        WHEN relkind='i' THEN '索引'\n                                        WHEN relkind='S' THEN '序列'\n                                        WHEN relkind='t' THEN 'TOAST表'\n                                        ELSE '其它' END AS 类型,\n                                   ROUND(relsize_total::NUMERIC / 1024, 2) AS \"估计空间占用(GB)\"\n                               FROM ${LogicInstance}.view_fact_polar_stat_relation_size\n                               WHERE time = (SELECT MAX(time) FROM ${LogicInstance}.view_fact_polar_stat_relation_size WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}')\n                                   AND physical_ins_name='${PhysicalInstance}' AND relsize_total > 0.01\n                               ORDER BY relsize_total DESC LIMIT 10"
      }
     ]
    },
    {
     "title": "Top 表年龄",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 147 },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "                           SELECT\n                                   dbname AS 数据库,\n                                   schemaname AS schema,\n                                   relname AS 表,\n                                   CASE WHEN relkind='r' THEN '表'\n                                        WHEN relkind='i' THEN '索引'\n                                        WHEN relkind='S' THEN '序列'\n                                        WHEN relkind='t' THEN 'TOAST表'\n                                        ELSE '其它' END AS 类型,\n                                   table_age::BIGINT AS value_年龄,\n                                   ROUND((table_age / 2147483647 * 100)::NUMERIC, 2) AS \"绕卷比例(%)\"\n                            FROM ${LogicInstance}.view_fact_polar_stat_table_age\n                            WHERE time = (SELECT MAX(time) FROM ${LogicInstance}.view_fact_polar_stat_table_age WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}')\n                            ORDER BY table_age DESC LIMIT 10"
      }
     ]
    },
    {
     "title": "Top 膨胀率",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 159 },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT\n                                   dbname AS 数据库,\n                                   schemaname AS schema,\n                                   relname AS 表,\n                                   n_live_tup::BIGINT AS 活跃元组,\n                                   n_dead_tup::BIGINT AS 死亡元组,\n                                   ROUND(dead_tup_ratio::NUMERIC, 2) AS \"死亡元组比例(%)\",\n                                   CASE WHEN last_vacuum<0.1 THEN '未做过' ELSE ROUND(((time - last_vacuum) / 60)::NUMERIC, 1)::TEXT END AS \"距上次vacuum(分钟)\",\n                                   CASE WHEN last_autovacuum<0.1 THEN '未做过' ELSE ROUND(((time - last_autovacuum) / 60)::NUMERIC, 1)::TEXT END AS \"距上次autovacuum(分钟)\"\n                               FROM ${LogicInstance}.view_fact_polar_stat_user_tables\n                               WHERE time = (SELECT MAX(time) FROM ${LogicInstance}.view_fact_polar_stat_user_tables WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}')\n                                   AND physical_ins_name='${PhysicalInstance}'\n                               ORDER BY dead_tup_ratio DESC LIMIT 10"
      }
     ]
    },
    {
     "title": "Top analyze后更新行数",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 171 },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "    SELECT\n                                   dbname AS 数据库,\n                                   schemaname AS schema,\n                                   relname AS 表,\n                                   n_mod_since_analyze::BIGINT AS analyze后更新行数,\n                                   CASE WHEN last_analyze<0.1 THEN '未做过' ELSE ROUND(((time - last_analyze) / 60)::NUMERIC, 1)::TEXT END AS \"距上次analyze(分钟)\\\",\n                                   CASE WHEN last_autoanalyze<0.1 THEN '未做过' ELSE ROUND(((time - last_autoanalyze) / 60)::NUMERIC, 1)::TEXT END AS \"距上次autoanalyze(分钟)\"\n                            FROM ${LogicInstance}.view_fact_polar_stat_user_tables\n                            WHERE time = (SELECT MAX(time) FROM ${LogicInstance}.view_fact_polar_stat_user_tables WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}')\n                            ORDER BY n_mod_since_analyze DESC LIMIT 10"
      }
     ]
    }
   ]
  },
  {
   "title": "Configuration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "数据库配置",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "constant": 6.5,
       "rawSql": "SELECT name AS 名称, source AS 来源, MAX(setting) AS 值, TO_CHAR(TO_TIMESTAMP(MAX(time)), 'YYYY-MM-DD HH24:MI:SS') AS 时间\n                               FROM ${LogicInstance}.view_fact_polar_settings\n                               WHERE time BETWEEN $__unixEpochFrom() AND $__unixEpochTo() AND physical_ins_name='${PhysicalInstance}' AND source NOT IN ('client', 'session')\n                               GROUP BY name, source\n                               ORDER BY\n                                   CASE source\n                                          WHEN 'configuration file' THEN 1\n                                          WHEN 'override' THEN 2\n                                          WHEN 'default' THEN 3\n                                          ELSE 4 END"
      }
     ]
    }
   ]
  }
 ]
}