{
 "title": "PolarDB-O 数据库开源版 (Prometheus)",
 "tags": [
  "PolarDB-O",
  "Prometheus",
  "DB"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "PrometheusDataSource", "label": "Prometheus数据源", "query": "prometheus" },
   {
    "name": "LogicInstance",
    "label": "逻辑实例id",
    "query": {
     "query": "query_result(count by (logical_insname) (count_over_time(polar_cpu_total[$__range])))"
    }
   },
   {
    "name": "PhysicalInstance",
    "label": "物理实例id",
    "query": {
     "query": "query_result(count by (physical_insname) (count_over_time(polar_cpu_total{logical_insname=~\"$LogicInstance\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "polar_cpu_total_usage{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "polar_mem_total_usage{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}"
    }
   ]
  },
  {
   "title": "磁盘IO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(polar_read_count {logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_info\", dim_fileloc=\"pfs\"}) + SUM(polar_write_count {logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_info\", dim_fileloc=\"pfs\"})"
    }
   ]
  },
  {
   "title": "空间使用率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "polar_fs_size_usage{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "polar_commits_delta+polar_rollbacks_delta{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}"
    }
   ]
  },
  {
   "title": "连接数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "polar_connections{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "sdd"
    }
   ]
  },
  {
   "title": "缓存命中率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "polar_blks_hit_delta{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"} / (polar_blks_hit_delta + polar_blks_read_delta{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}) * 100",
     "legendFormat": "sdd"
    }
   ]
  },
  {
   "title": "同步延迟",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "polar_replay_latency_in_mb{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}"
    }
   ]
  },
  {
   "title": "等待事件",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SUM(polar_wait_count{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}) BY (dim_wait_event, dim_wait_event_type) ",
     "legendFormat": "{{dim_wait_event_type}}:{{ dim_wait_event }}"
    }
   ]
  },
  { "title": "数据库资源", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "polar_cpu_user_usage{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "用户态"
    },
    {
     "expr": "polar_cpu_sys_usage{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "系统态"
    }
   ]
  },
  {
   "title": "CPU: 按进程类型堆叠",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "polar_backend_cpu{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "backend"
    },
    {
     "expr": "polar_checkpoint_cpu{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "checkpoint"
    },
    {
     "expr": "polar_bgwriter_cpu{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "bgwriter"
    },
    {
     "expr": "polar_logger_cpu{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "logger"
    },
    {
     "expr": "polar_pgstat_cpu{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "pgstat"
    },
    {
     "expr": "polar_walwriter_cpu{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "walwriter"
    },
    {
     "expr": "polar_postmaster_cpu{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "postmaster"
    },
    {
     "expr": "polar_walsender_cpu{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "walsender"
    },
    {
     "expr": "polar_walreceiver_cpu{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "walreceiver"
    },
    {
     "expr": "polar_startup_cpu{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "startup"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "polar_mem_total_usage{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "rss使用率"
    }
   ]
  },
  {
   "title": "内存使用量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "polar_mem_total_used{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "总内存使用量"
    }
   ]
  },
  {
   "title": "rss: 按进程类型堆叠",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "polar_backend_mem{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "backend"
    },
    {
     "expr": "polar_checkpoint_mem{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "checkpoint"
    },
    {
     "expr": "polar_bgwriter_mem{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "bgwriter"
    },
    {
     "expr": "polar_logger_mem{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "logger"
    },
    {
     "expr": "polar_pgstat_mem{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "pgstat"
    },
    {
     "expr": "polar_walwriter_mem{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "walwriter"
    },
    {
     "expr": "polar_postmaster_mem{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "postmaster"
    },
    {
     "expr": "polar_walsender_mem{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "walsender"
    },
    {
     "expr": "polar_walreceiver_mem{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "walreceiver"
    },
    {
     "expr": "polar_startup_mem{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "startup"
    }
   ]
  },
  {
   "title": "read iops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polar_read_count{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_info\", dim_fileloc=\"pfs\"}",
     "legendFormat": "{{ dim_filetype }} "
    }
   ]
  },
  {
   "title": "write iops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polar_write_count{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_info\", dim_fileloc=\"pfs\"}",
     "legendFormat": "{{ dim_filetype }}"
    }
   ]
  },
  {
   "title": "open iops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polar_open_count{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_info\", dim_fileloc=\"pfs\"}",
     "legendFormat": "{{ dim_filetype }}"
    }
   ]
  },
  {
   "title": "seek iops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polar_seek_count{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_info\", dim_fileloc=\"pfs\"}",
     "legendFormat": "{{ dim_filetype }}"
    }
   ]
  },
  {
   "title": "read bps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "polar_read_throughput{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_info\", dim_fileloc=\"pfs\"}",
     "legendFormat": "{{ dim_filetype }}"
    }
   ]
  },
  {
   "title": "write bps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "polar_write_throughput{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_info\", dim_fileloc=\"pfs\"}",
     "legendFormat": "{{ dim_filetype }}"
    }
   ]
  },
  {
   "title": "read 延迟分布",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polar_num_lessthan200us{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"read\"}\n\n",
     "legendFormat": "(0us, 200us]"
    },
    {
     "expr": "polar_num_lessthan400us{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"read\"}\n\n",
     "legendFormat": "(200us, 400us]"
    },
    {
     "expr": "polar_num_lessthan1ms{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"read\"}\n",
     "legendFormat": "(400us, 1ms]"
    },
    {
     "expr": "polar_num_lessthan10ms{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"read\"}\n",
     "legendFormat": "(1ms, 10ms]"
    },
    {
     "expr": "polar_num_lessthan100ms{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"read\"}\n",
     "legendFormat": "(10ms, 100ms]"
    },
    {
     "expr": "polar_num_morethan100ms{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"read\"}\n",
     "legendFormat": "(100ms, inf.)"
    }
   ]
  },
  {
   "title": "write 延迟分布",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polar_num_lessthan200us{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"write\"}\n\n",
     "legendFormat": "(0us, 200us]"
    },
    {
     "expr": "polar_num_lessthan400us{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"write\"}\n\n",
     "legendFormat": "(200us, 400us]"
    },
    {
     "expr": "polar_num_lessthan1ms{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"write\"}\n",
     "legendFormat": "(400us, 1ms]"
    },
    {
     "expr": "polar_num_lessthan10ms{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"write\"}\n",
     "legendFormat": "(1ms, 10ms]"
    },
    {
     "expr": "polar_num_lessthan100ms{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"write\"}\n",
     "legendFormat": "(10ms, 100ms]"
    },
    {
     "expr": "polar_num_morethan100ms{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"write\"}\n",
     "legendFormat": "(100ms, inf.)"
    }
   ]
  },
  {
   "title": "open 延迟分布",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polar_num_lessthan200us{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"open\"}\n\n",
     "legendFormat": "(0us, 200us]"
    },
    {
     "expr": "polar_num_lessthan400us{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"open\"}\n\n",
     "legendFormat": "(200us, 400us]"
    },
    {
     "expr": "polar_num_lessthan1ms{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"open\"}\n",
     "legendFormat": "(400us, 1ms]"
    },
    {
     "expr": "polar_num_lessthan10ms{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"open\"}\n",
     "legendFormat": "(1ms, 10ms]"
    },
    {
     "expr": "polar_num_lessthan100ms{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"open\"}\n",
     "legendFormat": "(10ms, 100ms]"
    },
    {
     "expr": "polar_num_morethan100ms{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"open\"}\n",
     "legendFormat": "(100ms, inf.)"
    }
   ]
  },
  {
   "title": "seek 延迟分布",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polar_num_lessthan200us{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"seek\"}\n\n",
     "legendFormat": "(0us, 200us]"
    },
    {
     "expr": "polar_num_lessthan400us{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"seek\"}\n\n",
     "legendFormat": "(200us, 400us]"
    },
    {
     "expr": "polar_num_lessthan1ms{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"seek\"}\n",
     "legendFormat": "(400us, 1ms]"
    },
    {
     "expr": "polar_num_lessthan10ms{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"seek\"}\n",
     "legendFormat": "(1ms, 10ms]"
    },
    {
     "expr": "polar_num_lessthan100ms{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"seek\"}\n",
     "legendFormat": "(10ms, 100ms]"
    },
    {
     "expr": "polar_num_morethan100ms{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"polar_stat_io_latency\", dim_iotype=\"seek\"}\n",
     "legendFormat": "(100ms, inf.)"
    }
   ]
  },
  {
   "title": "文件系统使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "polar_size_usage{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "空间"
    },
    {
     "expr": "polar_inodes_usage{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "inode"
    }
   ]
  },
  {
   "title": "空间分布",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "polar_polar_wal_dir_size{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "数据目录"
    },
    {
     "expr": "polar_polar_base_dir_size{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\"}",
     "legendFormat": "WAL目录"
    }
   ]
  },
  { "title": "数据库指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "连接",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polar_connections{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "总连接数"
    },
    {
     "expr": "polar_active_connections{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "活跃连接数"
    },
    {
     "expr": "polar_idle_connections{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "空闲连接数"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polar_commits_delta{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "提交"
    },
    {
     "expr": "polar_rollbacks_delta{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "回滚"
    }
   ]
  },
  {
   "title": "事务状态",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polar_active_transactions{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "活跃事务"
    },
    {
     "expr": "polar_idle_transactions{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "空闲事务数"
    }
   ]
  },
  {
   "title": "行",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polar_tup_deleted_delta{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "删除行数"
    },
    {
     "expr": "polar_tup_fetched_delta{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "返回行数"
    },
    {
     "expr": "polar_tup_returned_delta{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "扫描行数"
    },
    {
     "expr": "polar_tup_inserted_delta{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "插入行数"
    },
    {
     "expr": "polar_tup_updated_delta{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "更新行数"
    }
   ]
  },
  {
   "title": "数据库读",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polar_blks_hit_delta{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "命中缓存读"
    },
    {
     "expr": "polar_blks_read_delta{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "磁盘读"
    }
   ]
  },
  {
   "title": "数据库写",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polar_buffers_checkpoint_delta{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "checkpoint写"
    },
    {
     "expr": "polar_buffers_backend_delta{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "backend写"
    },
    {
     "expr": "polar_buffers_clean_delta{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "bgwriter写"
    }
   ]
  },
  {
   "title": "长事务数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polar_three_seconds_transactions{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "持续三秒长事务"
    },
    {
     "expr": "polar_one_second_transactions{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "持续一秒长事务"
    },
    {
     "expr": "polar_five_seconds_long_transactions{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "持续五秒的长事务"
    },
    {
     "expr": "polar_three_seconds_idle_transactions{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "持续三秒的空闲长事务"
    },
    {
     "expr": "polar_one_second_idle_transactions{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "持续一秒的空闲长事务"
    },
    {
     "expr": "polar_five_seconds_idle_transactions{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "持续五秒的空闲长事务"
    }
   ]
  },
  {
   "title": "慢SQL数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polar_three_seconds_executing_sqls{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "执行超过三秒的慢SQL数"
    },
    {
     "expr": "polar_one_second_executing_sqls{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "执行超过一秒的慢SQL数"
    },
    {
     "expr": "polar_five_seconds_long_transactions{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "执行超过五秒的慢SQL数"
    }
   ]
  },
  {
   "title": "最长事务持续时间",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "polar_swell_time{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "最长事务持续时间"
    }
   ]
  },
  {
   "title": "临时文件数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polar_temp_files_delta{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "临时文件数"
    }
   ]
  },
  {
   "title": "数据库年龄",
   "type": "graph",
   "description": "事务数最多为2的31次方, 用尽数据库将无法提供服务, 该指标表示是未回收的事务数",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polar_db_age{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "xids"
    }
   ]
  },
  {
   "title": "非活跃复制槽",
   "type": "graph",
   "description": "非活跃复制槽会阻塞WAL文件回收, 造成空间膨胀",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 121 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polar_inactive_slots{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "非活跃复制槽数量"
    }
   ]
  },
  {
   "title": "最大同步延迟",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "polar_replay_latency_in_mb{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "回放延迟"
    },
    {
     "expr": "polar_send_latency_in_mb{logical_insname=\"$LogicInstance\", physical_insname=\"$PhysicalInstance\", datamodel=\"dbmetrics\"}",
     "legendFormat": "发送延迟"
    }
   ]
  }
 ]
}